### ISSUE TITLE
Hash algorithm now deprecated in Node 6.0

### ISSUE THREAD

**Issue by colinskow** [zemirco/couch-pwd#1]
Running this will now generate:
`(node:44527) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest`

The default digest is `'sha1'`. (I checked the Node source code to make sure.) You need to specify it explicitly or this library will no longer work in Node 7.

``` js
crypto.pbkdf2(pwd, salt, iterations, keylen, 'sha1', function(err, hash){
        if (err) return cb(err);
        cb(null, salt, hash.toString(encoding));
      });
```

**Comment by ybian** [comment]
Hey @colinskow I'm running into this same issue after upgrading to NodeJS 6 with superlogin. Nice to see you here. ;-) Unfortunately there is no response after more than 2 months. This library seems not maintained any more. Maybe you should consider dropping dependency on this (fork it, write the util function by self, or use something else)?

**Comment by colinskow** [comment]
We are fine until Node 7 comes out. I will fork it and fix it--very simple.
